# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
specs/openapi-joined.json:
  operation-4xx-response:
    - '#/paths/~1v1~1openapi.json/get/responses'
    - '#/paths/~1v1~1property-data-types/get/responses'
    - '#/paths/~1v0~1search~1items/get/responses'
